version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - '15432:5432'
    container_name: pocket-link
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pocket_link