// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: urls.sql

package db

import (
	"context"
)

const createUrl = `-- name: CreateUrl :one
INSERT INTO urls (
    long_url,
    short_url
) VALUES (
  $1, $2
)
RETURNING id, long_url, short_url, created_at, updated_at
`

type CreateUrlParams struct {
	LongUrl  string `json:"long_url"`
	ShortUrl string `json:"short_url"`
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createUrl, arg.LongUrl, arg.ShortUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.LongUrl,
		&i.ShortUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUrl = `-- name: GetUrl :one
SELECT id, long_url, short_url, created_at, updated_at FROM urls
WHERE short_url = $1 LIMIT 1
`

func (q *Queries) GetUrl(ctx context.Context, shortUrl string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getUrl, shortUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.LongUrl,
		&i.ShortUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
